const data = [
  {
    "lang": "C++",
    "yr": 1983,
    "invent": "Bjarne Stroustrup",
    "ver": "C++23",
    "use": "Game development, Systems programming, High-performance apps",
    "doc": "https://en.cppreference.com/w/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/306px-ISO_C%2B%2B_Logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb",
    "fram": ["Qt", "Unreal Engine", "JUCE"],
    "ref": "https://quickref.me/cpp"
  },
  {
    "lang": "Python",
    "yr": 1991,
    "invent": "Guido van Rossum",
    "ver": "3.12",
    "use": "Data science, AI/ML, Web development, Scripting",
    "doc": "https://docs.python.org/3/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL-osiE80TeTskkFv9bn9Xd805qjJ15iiA",
    "fram": ["Django", "Flask", "FastAPI"],
    "ref": "https://quickref.me/python"
  },
  {
    "lang": "JavaScript",
    "yr": 1995,
    "invent": "Brendan Eich",
    "ver": "ECMAScript 2024",
    "use": "Web development (Frontend/Backend), Mobile apps",
    "doc": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    "youtube": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9i9Ae2D9Ee1RvylH38dKuET",
    "fram": ["React", "Vue", "Node.js", "Express"],
    "ref": "https://quickref.me/javascript"
  },
  {
    "lang": "Java",
    "yr": 1995,
    "invent": "James Gosling",
    "ver": "Java 21 (LTS)",
    "use": "Enterprise systems, Android, Big Data",
    "doc": "https://docs.oracle.com/en/java/",
    "logo": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/1200px-Java_programming_language_logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLsyeobzWxl7pe_IiTfNyr55kwJPWbgxB5",
    "fram": ["Spring Boot", "Hibernate", "Jakarta EE"],
    "ref": "https://quickref.me/java"
  },
  {
    "lang": "C#",
    "yr": 2000,
    "invent": "Microsoft",
    "ver": "C# 12",
    "use": "Windows apps, Game dev (Unity), Web APIs",
    "doc": "https://learn.microsoft.com/en-us/dotnet/csharp/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Csharp_Logo.png/611px-Csharp_Logo.png",
    "youtube": "https://www.youtube.com/playlist?list=PLdo4fOcmZ0oVxKLQCHpiUWun7vlJJvUiN",
    "fram": ["ASP.NET Core", "Blazor", ".NET MAUI"],
    "ref": "https://quickref.me/cs"
  },
  {
    "lang": "Go",
    "yr": 2009,
    "invent": "Google",
    "ver": "Go 1.22",
    "use": "Cloud infrastructure, Microservices, DevOps tools",
    "doc": "https://go.dev/doc/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Go_Logo_Blue.svg/1200px-Go_Logo_Blue.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL9mg9S2uCKYj6a24A-q6yD64E7M9X-M9_",
    "fram": ["Gin", "Fiber", "Echo"],
    "ref": "https://quickref.me/golang"
  },
  {
    "lang": "Rust",
    "yr": 2010,
    "invent": "Graydon Hoare",
    "ver": "1.76",
    "use": "Systems programming, WebAssembly, CLI tools",
    "doc": "https://doc.rust-lang.org/book/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/1200px-Rust_programming_language_black_logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLai5B987bZ9CoVR-QEIN9foz4QCJ0H2Y8",
    "fram": ["Actix", "Axum", "Tauri"],
    "ref": "https://quickref.me/rust"
  },
  {
    "lang": "PHP",
    "yr": 1994,
    "invent": "Rasmus Lerdorf",
    "ver": "PHP 8.3",
    "use": "Server-side web scripting, CMS development",
    "doc": "https://www.php.net/docs.php",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/1200px-PHP-logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL0eyrZg-T0qExi8w5X_y2dydqD8s2xM1s",
    "fram": ["Laravel", "Symfony", "CodeIgniter"],
    "ref": "https://quickref.me/php"
  },
  {
    "lang": "TypeScript",
    "yr": 2012,
    "invent": "Microsoft",
    "ver": "5.4",
    "use": "Large-scale web apps, Static typing for JS",
    "doc": "https://www.typescriptlang.org/docs/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gUgr39Q_yD6v-bSyMwKPUI",
    "fram": ["Angular", "NestJS", "Next.js"],
    "ref": "https://quickref.me/typescript"
  },
  {
    "lang": "Kotlin",
    "yr": 2011,
    "invent": "JetBrains",
    "ver": "1.9",
    "use": "Android apps, Multiplatform mobile, Server-side",
    "doc": "https://kotlinlang.org/docs/home.html",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin_Icon.png/1200px-Kotlin_Icon.png",
    "youtube": "https://www.youtube.com/playlist?list=PLQkwcJG4YTCRSQikwhtoApYs9ij_Hc5Z9",
    "fram": ["Jetpack Compose", "Ktor", "Spring Boot"],
    "ref": "https://quickref.me/kotlin"
  },
  {
    "lang": "R",
    "yr": 1993,
    "invent": "Ross Ihaka & Robert Gentleman",
    "ver": "4.3",
    "use": "Statistical analysis, Data visualization, Bioinformatics",
    "doc": "https://cran.r-project.org/manuals.html",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/1200px-R_logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLqzoL9-eJTNBM28NYyLGP2Lr3Zk0x08Lz",
    "fram": ["Shiny", "ggplot2", "Tidyverse"],
    "ref": "https://quickref.me/r"
  },
  {
    "lang": "Dart",
    "yr": 2011,
    "invent": "Google",
    "ver": "3.3",
    "use": "Cross-platform mobile apps (Flutter), Web",
    "doc": "https://dart.dev/guides",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dart-logo.png/1200px-Dart-logo.png",
    "youtube": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9jLYyp2Aoh6hcWuxFDX6PBJ",
    "fram": ["Flutter", "AngularDart"],
    "ref": "https://quickref.me/dart"
  },
  {
    "lang": "Haskell",
    "yr": 1990,
    "invent": "Simon Peyton Jones et al.",
    "ver": "GHC 9.8",
    "use": "Academic research, Financial modeling, Compilers",
    "doc": "https://www.haskell.org/documentation/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Haskell-Logo.svg/1200px-Haskell-Logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLe7Ei6viL6jGp1Rfu0dil1JH1SHk9bgDV",
    "fram": ["Yesod", "Servant", "IHP"],
    "ref": "https://quickref.me/haskell"
  },
  {
    "lang": "Scala",
    "yr": 2004,
    "invent": "Martin Odersky",
    "ver": "3.3",
    "use": "Big Data (Spark), Distributed systems",
    "doc": "https://docs.scala-lang.org/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Scala-full-color.svg/1200px-Scala-full-color.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLJGDHERh23x-CXtpq97Wc38qI9o5jZ2X4",
    "fram": ["Play", "Akka", "Apache Spark"],
    "ref": "https://quickref.me/scala"
  },
  {
    "lang": "Perl",
    "yr": 1987,
    "invent": "Larry Wall",
    "ver": "5.38",
    "use": "Legacy web systems, Text processing, System admin",
    "doc": "https://perldoc.perl.org/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Perl_Language_Logo.svg/1200px-Perl_Language_Logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PLVGH6YvJnuzf2zi3f1Eyjfquf-f-V9yrW",
    "fram": ["Mojolicious", "Catalyst", "Dancer2"],
    "ref": "https://quickref.me/perl"
  },
  {
    "lang": "Objective-C",
    "yr": 1984,
    "invent": "Tom Love & Brad Cox",
    "ver": "2.0",
    "use": "Legacy iOS/macOS development",
    "doc": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/2/23/Objective-C_logo.png",
    "youtube": "https://www.youtube.com/playlist?list=PLxxA5z-8B2xk4szCgFmgonNcCboyNneMD",
    "fram": ["Cocoa", "Cocoa Touch"],
    "ref": "https://learnxinyminutes.com/docs/objective-c/"
  },
  {
    "lang": "Swift",
    "yr": 2014,
    "invent": "Apple Inc.",
    "ver": "5.10",
    "use": "Modern iOS/macOS/watchOS development",
    "doc": "https://www.swift.org/documentation/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Swift_logo.svg/1200px-Swift_logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL0eyrZg-T0qF608dD6Yp62dQ-c2XfM-7X",
    "fram": ["SwiftUI", "UIKit", "Vapor"],
    "ref": "https://quickref.me/swift"
  },
  {
    "lang": "Ruby",
    "yr": 1995,
    "invent": "Yukihiro Matsumoto",
    "ver": "3.3",
    "use": "Web development, Rapid prototyping",
    "doc": "https://ruby-doc.org/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/1200px-Ruby_logo.svg.png",
    "youtube": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hadYXjMvhAtfI222O0OQe7",
    "fram": ["Ruby on Rails", "Sinatra"],
    "ref": "https://quickref.me/ruby"
  }
];

export default data;